name: CI

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - "v*"
    # always run CI for tags
    tags:
      - "*"

env:
  CI: true

jobs:
  test-locked-deps:
    name: Locked Deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Browser Tests
        run: yarn test

  test-old-dependencies:
    name: Oldest Supported Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 8
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Browser Tests
        run: yarn test

  test-try:
    name: Ember Try
    runs-on: ubuntu-latest
    needs: [test-locked-deps]
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ember-lts-2.8
          - ember-lts-2.12
          - ember-release
          - ember-beta
        experimental: [false]
        include:
          - scenario: ember-canary
            experimental: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Try Scenario
        run: yarn ember try:one ${{ matrix.scenario }}
